export enum ENV {
  PORT = 'PORT',

  IS_PRODUCTION = 'IS_PRODUCTION',

  CLIENT_URL = 'CLIENT_URL',

  CORS_ORIGIN = 'CORS_ORIGIN',
  CORS_HEADERS = 'CORS_HEADERS',
  CORS_CREDENTIALS = 'CORS_CREDENTIALS',
  CORS_METHODS = 'CORS_METHODS',

  DATABASE_URL = 'DATABASE_URL',
}
