export enum ENV {
  PORT = 'PORT',

  IS_PRODUCTION = 'IS_PRODUCTION',

  CLIENT_URL = 'CLIENT_URL',

  CORS_ORIGIN = 'CORS_ORIGIN',
  CORS_HEADERS = 'CORS_HEADERS',
  CORS_CREDENTIALS = 'CORS_CREDENTIALS',
  CORS_METHODS = 'CORS_METHODS',

  DATABASE_URL = 'DATABASE_URL',

  JWT_ACCESS_SECRET = 'JWT_ACCESS_SECRET',
  JWT_REFRESH_SECRET = 'JWT_REFRESH_SECRET',
  JWT_ACCESS_TOKEN_EXPIRATION_TIME = 'JWT_ACCESS_TOKEN_EXPIRATION_TIME',
  JWT_REFRESH_TOKEN_EXPIRATION_TIME = 'JWT_REFRESH_TOKEN_EXPIRATION_TIME',
}
